# Generated by Django 5.1.4 on 2025-08-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=30)),
                ('Country', models.CharField(max_length=70)),
                ('PhonNumber', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
            ],
        ),
    ]
