# Generated by Django 5.1.4 on 2025-09-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sipage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.DateField(max_length=12)),
                ('PhonNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
