# Generated by Django 5.1.4 on 2025-09-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_sipage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sipage',
        ),
    ]
