# Generated by Django 5.1.4 on 2025-09-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_delete_sipage'),
    ]

    operations = [
        migrations.CreateModel(
            name='sidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=6)),
                ('phonnumber', models.CharField(max_length=11)),
            ],
        ),
    ]
