# Generated by Django 5.1.4 on 2026-05-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_sidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sidata',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
