# Generated by Django 5.1.4 on 2026-05-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_anime_alter_sidata_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
