# Generated by Django 5.1.4 on 2026-05-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_delete_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='anime/')),
                ('chapters', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('page', models.CharField(max_length=50)),
            ],
        ),
    ]
