# Generated by Django 5.1.4 on 2026-05-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('page', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
