# Generated by Django 5.1.4 on 2026-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_product_delete_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=30)),
                ('eml', models.EmailField(max_length=30)),
                ('pas', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='shopproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chapter', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='anime/')),
            ],
        ),
    ]
