# Generated by Django 5.1.4 on 2026-05-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_page_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(choices=[('shop', 'Shop'), ('shop1', 'Shop1'), ('shop2', 'Shop2'), ('shop3', 'Shop3'), ('shop4', 'Shop4')], default='shop', max_length=20),
            preserve_default=False,
        ),
    ]
