# Generated by Django 5.1.4 on 2026-05-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_shopproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('suggestion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
