# Generated by Django 6.1 on 2026-09-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_sidata_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', help_text='Emoji or icon identifier', max_length=50)),
                ('points_reward', models.PositiveIntegerField(default=50)),
                ('badge_type', models.CharField(default='Bronze', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.FloatField(help_text='e.g. 1, 2.5, 100')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO code: en, hi, gu, ja, pa', max_length=10, unique=True)),
                ('name', models.CharField(help_text='English, Hindi, Gujarati, Japanese, Punjabi', max_length=50)),
                ('native_name', models.CharField(help_text='Native font representation', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.shopproduct'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='current_page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='total_pages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='isbn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='language_name',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='stock',
            field=models.PositiveIntegerField(default=50, help_text='Inventory available'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sidata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sidata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sidata',
            name='theme_preference',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='sidata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='userorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.shopproduct'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(choices=[('shop', 'Shop - All Items'), ('shop1', 'Shop1 - Shonen & Action'), ('shop2', 'Shop2 - Seinen & Dark Fantasy'), ('shop3', 'Shop3 - Romance & Slice of Life'), ('shop4', 'Shop4 - Collector Editions & Box Sets')], default='shop', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='chapter',
            field=models.CharField(help_text='e.g. Vol 1-10 or 100 Chapters', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.CharField(help_text='Price in $ or ₹', max_length=20),
        ),
        migrations.AlterField(
            model_name='sidata',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sidata',
            name='phonnumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('Placed', 'Order Placed'), ('Confirmed', 'Order Confirmed'), ('Processing', 'Processing / Packing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Replacement Requested', 'Replacement Requested'), ('Return Approved', 'Return Approved'), ('Replacement Approved', 'Replacement Approved'), ('Returned & Refunded', 'Returned & Refunded'), ('Replacement Dispatched', 'Replacement Dispatched')], default='Placed', max_length=50),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='work.sidata')),
            ],
        ),
        migrations.AddField(
            model_name='userorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='work.address'),
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alternative_title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='anime/covers/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='anime/banners/')),
                ('status', models.CharField(choices=[('Airing', 'Currently Airing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], default='Completed', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('studio', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='animes', to='work.animegenre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='digital_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='work.language'),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alternative_title', models.CharField(blank=True, help_text='Japanese / Romanized title', max_length=200, null=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='manga/covers/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='manga/banners/')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Hiatus', 'Hiatus')], default='Ongoing', max_length=20)),
                ('manga_type', models.CharField(choices=[('Manga', 'Japanese Manga'), ('Manhwa', 'Korean Manhwa'), ('Manhua', 'Chinese Manhua')], default='Manga', max_length=20)),
                ('age_rating', models.CharField(default='All Ages', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangas', to='work.artist')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangas', to='work.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='mangas', to='work.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='work.manga'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='digital_manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to='work.manga'),
        ),
        migrations.CreateModel(
            name='MangaVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='manga/volumes/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='work.manga')),
            ],
            options={
                'ordering': ['volume_number'],
                'unique_together': {('manga', 'volume_number')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='work.mangavolume'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order', 'Order Status Update'), ('manga', 'New Manga Chapter'), ('anime', 'New Anime Episode'), ('achievement', 'Achievement Unlocked'), ('system', 'System Announcement')], default='system', max_length=20)),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='work.sidata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='work.userorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='work.shopproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='work.anime')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('anime', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='anime/episodes/')),
                ('duration_seconds', models.PositiveIntegerField(default=1440, help_text='e.g. 1440 for 24 min')),
                ('video_url', models.URLField(blank=True, help_text='Direct MP4 / HLS / Embed Stream URL', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='anime/videos/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='work.anime')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='work.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('anime', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='ChapterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='manga/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='work.chapter')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('chapter', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.FloatField(default=1.0)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='work.sidata')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='work.chapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='work.manga')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'manga', 'chapter_number', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='MangaLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_title', models.CharField(blank=True, max_length=200, null=True)),
                ('translator_notes', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_versions', to='work.language')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_versions', to='work.manga')),
            ],
            options={
                'unique_together': {('manga', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MangaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating between 1 and 5')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='work.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_reviews', to='work.sidata')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'manga')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('manga', 'language', 'chapter_number')},
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating between 1 and 5')),
                ('review_text', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.userorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='work.shopproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='work.sidata')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='work.sidata')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Currently Reading'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('plan_to_read', 'Plan to Read')], default='reading', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_libraries', to='work.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='work.sidata')),
            ],
            options={
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'manga')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position_seconds', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=1440)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.anime')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='work.sidata')),
            ],
            options={
                'ordering': ['-last_watched_at'],
                'unique_together': {('user', 'anime', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wishlists', to='work.shopproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='work.sidata')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
